### ISSUE TITLE
[BUG] Pypi Windows installation : only 1.0.9 install

### ISSUE THREAD

**Issue by Kochise** [davidmarble/virtualenvwrapper-win#117]
Trying to install `virtualenvwrapper-win` :

```batch
Microsoft Windows [version 10.0.19042.1165]
(c) Microsoft Corporation. Tous droits réservés.

C:\Program Files\Spyder\Python>python --version
Python 3.7.9

C:\Program Files\Spyder\Python>python -m pip install --upgrade pip
Requirement already satisfied: pip in c:\program files\spyder\python\lib\site-packages (21.2.4)

C:\Program Files\Spyder\Python>python -m pip install --upgrade virtualenvwrapper-win
Collecting virtualenvwrapper-win
  Downloading virtualenvwrapper-win-1.2.6.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_e5d0685d76c14c599614b8eb80434751\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_e5d0685d76c14c599614b8eb80434751\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-7zjzq1w8'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_e5d0685d76c14c599614b8eb80434751\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_e5d0685d76c14c599614b8eb80434751\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d3/07/7599a80e13e58e0bb561ed03c55a2a84872b64ae50cbc40d9bf7ebabbdd9/virtualenvwrapper-win-1.2.6.tar.gz#sha256=bdd445573b35d0a7e4f6a5fbc52a78cb48cc7abcd934cc3ac875b275dfe98eb4 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.2.5.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_d72ce5b4a8f44fe3b757b96bef80a303\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_d72ce5b4a8f44fe3b757b96bef80a303\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-_5buzjrg'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_d72ce5b4a8f44fe3b757b96bef80a303\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_d72ce5b4a8f44fe3b757b96bef80a303\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f5/23/4cba98733b9122219ce67177d745e4984b524b867cf3728eaa807ea21919/virtualenvwrapper-win-1.2.5.tar.gz#sha256=c54bec2874da571bacceabc1ebf5d474fe1c37786cb1ef23cdac9f3de9bfd6d8 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.2.4.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_442ec65c2ec449569dd58c260ef3062d\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_442ec65c2ec449569dd58c260ef3062d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-ru5rkf75'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_442ec65c2ec449569dd58c260ef3062d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_442ec65c2ec449569dd58c260ef3062d\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/a1/0d/ce1ce5a026365b6f8ae265c97a43ccb1245a082135c2a38d07af5df781d2/virtualenvwrapper-win-1.2.4.tar.gz#sha256=49005688cef9ff74615fe98437f3faea87279056669751145fc589f825a82cb5 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.2.3.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_d85797f4fbc447019b45b69ed3f0086f\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_d85797f4fbc447019b45b69ed3f0086f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-ywc9seh3'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_d85797f4fbc447019b45b69ed3f0086f\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_d85797f4fbc447019b45b69ed3f0086f\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ea/70/a939796269d9eba5983ec3d18e1f456861eb87ef653f28b1b8e6c5921559/virtualenvwrapper-win-1.2.3.tar.gz#sha256=74f5129b922c72fe593ef46db38eca3ce1c23d81a0030d6eee7911a3979b53b4 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.2.2.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_09874c4d6305428fbfda40657313060d\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_09874c4d6305428fbfda40657313060d\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-f181m2p7'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_09874c4d6305428fbfda40657313060d\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_09874c4d6305428fbfda40657313060d\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/16/0a/4a771999e044cac9a53014766185499dad16db6d90a06f4380d838fd2e00/virtualenvwrapper-win-1.2.2.tar.gz#sha256=e3cfabcda032474274211faed717ce04aa67faeaaa5d9467ffd3d62fe2151052 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.2.1.zip (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_3d5ada36603c4044b4ad00875aaee561\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_3d5ada36603c4044b4ad00875aaee561\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-ur03vzdc'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_3d5ada36603c4044b4ad00875aaee561\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_3d5ada36603c4044b4ad00875aaee561\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/af/f1/d2fbc0c65353e3aaa02dd414102158f097abe77c34df48e864ee7afef822/virtualenvwrapper-win-1.2.1.zip#sha256=0e0f2201178395f52d8acd813da0db17698a63d9b981f233940223265c85679e (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.2.0.zip (24 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_0f314b2dfd444fe5ad0c07ad15928978\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_0f314b2dfd444fe5ad0c07ad15928978\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-d66ujuu1'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_0f314b2dfd444fe5ad0c07ad15928978\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_0f314b2dfd444fe5ad0c07ad15928978\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/87/fc/38fbc32111d86659e0aeee3e8455ff1841a7c5245e7e64994033f1687b4e/virtualenvwrapper-win-1.2.0.zip#sha256=ed80061b3682ad1bff45840e1a01f642e3ae832b46c61a63600c33df23b76e3b (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.1.7.zip (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_269965f3799749b0bb6949d6521cfd3e\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_269965f3799749b0bb6949d6521cfd3e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-71rsyq23'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_269965f3799749b0bb6949d6521cfd3e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_269965f3799749b0bb6949d6521cfd3e\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/72/85/8e92ca2d7f5a75dd2d8e5303e5fe12e497be9c8b28dd05ef0776ccb35d78/virtualenvwrapper-win-1.1.7.zip#sha256=4dcb1a2fb3d37654ab6004d09f520ca46fb46ee0d51c5a89d2d1ac96fab84223 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.1.6.zip (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_df9b09efb8374c0885c7195c11b2b5b8\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_df9b09efb8374c0885c7195c11b2b5b8\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-g5wig6hq'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_df9b09efb8374c0885c7195c11b2b5b8\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_df9b09efb8374c0885c7195c11b2b5b8\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b1/3e/2458caa0cc8dc84bf36e0ab24417f1a00452097f23d059ce847b6d69643e/virtualenvwrapper-win-1.1.6.zip#sha256=905e3e457aa260850473327abe0c11b551fb753b8e0f6e0c7a1a86c50b0d4464 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.1.5.zip (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_6eaa535ee783460d83645b96751d9d61\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_6eaa535ee783460d83645b96751d9d61\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-n102441p'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_6eaa535ee783460d83645b96751d9d61\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_6eaa535ee783460d83645b96751d9d61\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f0/83/6eb5d3fd4a08877f1a1e61f52ad5c4cd12ab32d7b69d27346618d00d0016/virtualenvwrapper-win-1.1.5.zip#sha256=d513ae02730e49db1ee973c4eab3b2eafa92d38a1655c9cb63aea2b7f0454523 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.1.4.zip (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_ebc7f6091c44400aa017c8d3e120eb7b\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_ebc7f6091c44400aa017c8d3e120eb7b\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-kg9f2rml'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_ebc7f6091c44400aa017c8d3e120eb7b\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_ebc7f6091c44400aa017c8d3e120eb7b\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/0d/28/ddbe2aa209eb81db86871d062850f6b1c4fdb57994246be725dab885985a/virtualenvwrapper-win-1.1.4.zip#sha256=39db0814951a16598f10da3ce4f7b7d41910d4aeec762167b2d3ba831db8116c (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.1.3.zip (23 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Program Files\Spyder\Python\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_69107640d6db44e1bab34e050d82769e\\setup.py'"'"'; __file__='"'"'C:\\Users\\dkoch\\AppData\\Local\\Temp\\pip-install-96skz3fl\\virtualenvwrapper-win_69107640d6db44e1bab34e050d82769e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\dkoch\AppData\Local\Temp\pip-pip-egg-info-az3n22kq'
         cwd: C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_69107640d6db44e1bab34e050d82769e\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\dkoch\AppData\Local\Temp\pip-install-96skz3fl\virtualenvwrapper-win_69107640d6db44e1bab34e050d82769e\setup.py", line 3, in <module>
        from distribute_setup import use_setuptools
    ModuleNotFoundError: No module named 'distribute_setup'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/65/cd/dccea14df95ea17185350c9acc364237bf62ec649f82ddff86adc3b7bce3/virtualenvwrapper-win-1.1.3.zip#sha256=5c4f9ce7bb3bd294efcb6742f157402c4d1f07de054cd8b1aa646b815efb6942 (from https://pypi.org/simple/virtualenvwrapper-win/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading virtualenvwrapper-win-1.0.9.zip (15 kB)
Requirement already satisfied: virtualenv in c:\program files\spyder\python\lib\site-packages (from virtualenvwrapper-win) (20.8.0)
Requirement already satisfied: six<2,>=1.9.0 in c:\program files\spyder\pkgs (from virtualenv->virtualenvwrapper-win) (1.16.0)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\program files\spyder\python\lib\site-packages (from virtualenv->virtualenvwrapper-win) (3.0.12)
Requirement already satisfied: platformdirs<3,>=2 in c:\program files\spyder\pkgs (from virtualenv->virtualenvwrapper-win) (2.3.0)
Requirement already satisfied: backports.entry-points-selectable>=1.0.4 in c:\program files\spyder\python\lib\site-packages (from virtualenv->virtualenvwrapper-win) (1.1.0)
Requirement already satisfied: importlib-metadata>=0.12 in c:\program files\spyder\pkgs (from virtualenv->virtualenvwrapper-win) (4.8.1)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\program files\spyder\python\lib\site-packages (from virtualenv->virtualenvwrapper-win) (0.3.2)
Requirement already satisfied: zipp>=0.5 in c:\program files\spyder\pkgs (from importlib-metadata>=0.12->virtualenv->virtualenvwrapper-win) (3.5.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\program files\spyder\pkgs (from importlib-metadata>=0.12->virtualenv->virtualenvwrapper-win) (3.10.0.2)
Building wheels for collected packages: virtualenvwrapper-win
  Building wheel for virtualenvwrapper-win (setup.py) ... done
  Created wheel for virtualenvwrapper-win: filename=virtualenvwrapper_win-1.0.9-py3-none-any.whl size=10343 sha256=cbfd552b8b439708fe71a5515219732c0d466d9462f3469aaf8545e17ed55d13
  Stored in directory: c:\users\dkoch\appdata\local\pip\cache\wheels\a3\22\fc\380c9d91c56dd0d62fdea759cd15eb7ea487796f61aea4c9ef
Successfully built virtualenvwrapper-win
Installing collected packages: virtualenvwrapper-win
Successfully installed virtualenvwrapper-win-1.0.9

C:\Program Files\Spyder\Python>
```

**Comment by Kochise** [comment]
Copy `distribute_setup.py` from https://gist.github.com/elijah/bc00d6b43365ec4278ab into `c:\Program Files\Spyder\Python\Lib\site-packages\` (where `filelock.py` is) and retry installing...

```batch
Microsoft Windows [version 10.0.19042.1165]
(c) Microsoft Corporation. Tous droits réservés.

C:\Program Files\Spyder\Python>python -m pip install --upgrade virtualenvwrapper-win
Collecting virtualenvwrapper-win
  Using cached virtualenvwrapper-win-1.2.6.tar.gz (21 kB)
Requirement already satisfied: virtualenv in c:\program files\spyder\python\lib\site-packages (from virtualenvwrapper-win) (20.8.0)
Requirement already satisfied: importlib-metadata>=0.12 in c:\program files\spyder\pkgs (from virtualenv->virtualenvwrapper-win) (4.8.1)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\program files\spyder\python\lib\site-packages (from virtualenv->virtualenvwrapper-win) (3.0.12)
Requirement already satisfied: backports.entry-points-selectable>=1.0.4 in c:\program files\spyder\python\lib\site-packages (from virtualenv->virtualenvwrapper-win) (1.1.0)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\program files\spyder\python\lib\site-packages (from virtualenv->virtualenvwrapper-win) (0.3.2)
Requirement already satisfied: six<2,>=1.9.0 in c:\program files\spyder\pkgs (from virtualenv->virtualenvwrapper-win) (1.16.0)
Requirement already satisfied: platformdirs<3,>=2 in c:\program files\spyder\pkgs (from virtualenv->virtualenvwrapper-win) (2.3.0)
Requirement already satisfied: typing-extensions>=3.6.4 in c:\program files\spyder\pkgs (from importlib-metadata>=0.12->virtualenv->virtualenvwrapper-win) (3.10.0.2)
Requirement already satisfied: zipp>=0.5 in c:\program files\spyder\pkgs (from importlib-metadata>=0.12->virtualenv->virtualenvwrapper-win) (3.5.0)
Building wheels for collected packages: virtualenvwrapper-win
  Building wheel for virtualenvwrapper-win (setup.py) ... done
  Created wheel for virtualenvwrapper-win: filename=virtualenvwrapper_win-1.2.6-py3-none-any.whl size=18630 sha256=ef050e458e91157e60a1e9bab7709ae72616696c71f676138e4ef2c339bac2b9
  Stored in directory: c:\users\dkoch\appdata\local\pip\cache\wheels\56\8d\dc\8f5ba062cc9ee89f4cac15256b2df7b2cf4280eb74e10d3544
Successfully built virtualenvwrapper-win
Installing collected packages: virtualenvwrapper-win
Successfully installed virtualenvwrapper-win-1.2.6

C:\Program Files\Spyder\Python>
```

**Comment by thebjorn** [comment]
I can't reproduce with python.org's python:
```
go|C:\> py -3.7 -V
Python 3.7.4

go|C:\> py -3.7 -m pip -V
pip 21.2.4 from C:\Users\bp.DATAKORTET\AppData\Local\Programs\Python\Python37\lib\site-packages\pip (python 3.7)

go|C:\> py -3.7 -m pip install virtualenvwrapper-win
Looking in indexes: https://pypi.org/simple, http://pypi.norsktest.xyz
Collecting virtualenvwrapper-win
  Using cached virtualenvwrapper-win-1.2.6.tar.gz (21 kB)
Collecting virtualenv
  Downloading virtualenv-20.8.0-py2.py3-none-any.whl (5.3 MB)
     |████████████████████████████████| 5.3 MB 1.6 MB/s
Collecting six<2,>=1.9.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting backports.entry-points-selectable>=1.0.4
  Downloading backports.entry_points_selectable-1.1.0-py2.py3-none-any.whl (6.2 kB)
Collecting importlib-metadata>=0.12
  Downloading importlib_metadata-4.8.1-py3-none-any.whl (17 kB)
Collecting platformdirs<3,>=2
  Downloading platformdirs-2.3.0-py3-none-any.whl (13 kB)
Collecting filelock<4,>=3.0.0
  Using cached filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.2-py2.py3-none-any.whl (338 kB)
     |████████████████████████████████| 338 kB 6.8 MB/s
Requirement already satisfied: typing-extensions>=3.6.4 in c:\users\bp.datakortet\appdata\local\programs\python\python37\lib\site-packages (from importlib-metadata>=0.12->virtualenv->virtualenvwrapper-win) (3.7.4)
Collecting zipp>=0.5
  Downloading zipp-3.5.0-py3-none-any.whl (5.7 kB)
Using legacy 'setup.py install' for virtualenvwrapper-win, since package 'wheel' is not installed.
Installing collected packages: zipp, importlib-metadata, six, platformdirs, filelock, distlib, backports.entry-points-selectable, virtualenv, virtualenvwrapper-win
  WARNING: The script virtualenv.exe is installed in 'C:\Users\bp.DATAKORTET\AppData\Local\Programs\Python\Python37\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for virtualenvwrapper-win ... done
Successfully installed backports.entry-points-selectable-1.1.0 distlib-0.3.2 filelock-3.0.12 importlib-metadata-4.8.1 platformdirs-2.3.0 six-1.16.0 virtualenv-20.8.0 virtualenvwrapper-win-1.2.6 zipp-3.5.0
```
