### ISSUE TITLE
Update virtualenv dependency

### ISSUE THREAD

**Issue by dpantele** [davidmarble/virtualenvwrapper-win#41]
virtualenvwrapper-win requires virtualenv==1.9.1, which doesn't work on python 3.4:

```
C:\Users\dpantele\temp>virtualenv temp_test
Using base prefix 'C:\\Python34'
New python executable in temp_test\Scripts\python.exe
Failed to import the site module
Traceback (most recent call last):
  File "C:\Users\dpantele\temp\temp_test\lib\site.py", line 67, in <module>
    import os
  File "C:\Users\dpantele\temp\temp_test\lib\os.py", line 634, in <module>
    from _collections_abc import MutableMapping
ImportError: No module named '_collections_abc'
ERROR: The executable temp_test\Scripts\python.exe is not functioning
ERROR: It thinks sys.prefix is 'c:\\users\\dpantele\\temp' (should be 'c:\\users
\\dpantele\\temp\\temp_test')
ERROR: virtualenv is not compatible with this system or executable
Note: some Windows users have reported this error when they installed Python for
 "Only this user" or have multiple versions of Python installed. Copying the app
ropriate PythonXX.dll to the virtualenv Scripts/ directory may fix this problem.
```

**Comment by davidmarble** [comment]
I merged a pull request today that should fix this issue. I've uploaded the latest to pypi so you should be able to just `pip install -U virtualenvwrapper-win`

**Comment by denissss** [comment]
Cool!
But why behaviour of "workon" changed so it CDs to virtualenv directory ?
quite often I'm already in desired directory of project and just had to type "workon venv" so I was activating venv in place where I needed it.

Now I have to make couple additional steps to CD in project dir. :\

**Comment by utek** [comment]
@denissss Can you report it in another issue?
