### ISSUE TITLE
virtualenvwrapper-win won't install with pip (python 2.7.1)

### ISSUE THREAD

**Issue by bbigras** [davidmarble/virtualenvwrapper-win#6]
I got `No distributions at all found for virtualenvwrapper-win` when trying to install virtualenvwrapper-win with pip. I was able to install it by doing `pip install https://github.com/davidmarble/virtualenvwrapper-win/zipball/master`.

```
C:\>pip install virtualenvwrapper-win
Downloading/unpacking virtualenvwrapper-win
  Could not find any downloads that satisfy the requirement virtualenvwrapper-win
No distributions at all found for virtualenvwrapper-win
Storing complete log in q:\AppData\pip\pip.log
```

pip.log

```
Downloading/unpacking virtualenvwrapper-win
  Getting page http://pypi.python.org/simple/virtualenvwrapper-win
  URLs to search for versions for virtualenvwrapper-win:
  * http://pypi.python.org/simple/virtualenvwrapper-win/
  Getting page https://github.com/davidmarble/virtualenvwrapper-win/
  Analyzing links from page http://pypi.python.org/simple/virtualenvwrapper-win/
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/ (from http://pypi.python.org/simple/virtualenvwrapper-win/); not a file
    Skipping link http://www.doughellmann.com/projects/virtualenvwrapper/ (from http://pypi.python.org/simple/virtualenvwrapper-win/); not a file
  Analyzing links from page https://github.com/davidmarble/virtualenvwrapper-win/
    Skipping link https://github.com/opensearch.xml (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .xml
    Skipping link https://github.com/fluidicon.png (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .png
    Skipping link https://github.com/favicon.ico (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .ico
    Skipping link https://a248.e.akamai.net/assets.github.com/stylesheets/bundles/github-c2f83c57a14d5e54d816673f52563d987fe2821f.css (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .css
    Skipping link https://a248.e.akamai.net/assets.github.com/stylesheets/bundles/github2-34d96ae148c427d3106177152ac475d7df36c780.css (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .css
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/tree/ea742e6a561651e02ec27e79c542caca3d907cd1 (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/commits/master.atom (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .atom
    Skipping link https://github.com (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/plans (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/explore (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/features (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/blog (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/login?return_to=%2Fdavidmarble%2Fvirtualenvwrapper-win%2F (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/login?return_to=%2Fdavidmarble%2Fvirtualenvwrapper-win (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/watchers (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/network (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/pulls (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/issues (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/graphs (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/languages/Shell (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/#readme (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http:// (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/zipball/master (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win.git (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .git
    Skipping link git://github.com/davidmarble/virtualenvwrapper-win.git (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .git
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/dismiss-tree-finder-help (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/tags (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/downloads (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link javascript:; (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/tree/master (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/commits/master (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/branches (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/commit/ea742e6a561651e02ec27e79c542caca3d907cd1 (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/commits/master/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/tree/ea742e6a561651e02ec27e79c542caca3d907cd1/scripts (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/commit/d91ef4370da6647647b2806e5d89f3b4ed960c0a (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/blob/ea742e6a561651e02ec27e79c542caca3d907cd1/.gitignore (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/blob/ea742e6a561651e02ec27e79c542caca3d907cd1/README.rst (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .rst
    Skipping link https://github.com/davidmarble/virtualenvwrapper-win/blob/ea742e6a561651e02ec27e79c542caca3d907cd1/setup.py (from https://github.com/davidmarble/virtualenvwrapper-win/); unknown archive format: .py
    Skipping link http://pypi.python.org/pypi/virtualenv (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/about (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/contact (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/training (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://enterprise.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://status.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://get.gaug.es/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://speakerdeck.com (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://gist.github.com (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://mac.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://mobile.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://jobs.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://shop.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://octodex.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://help.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://developer.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://github.github.com/github-flavored-markdown/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://pages.github.com/ (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/site/terms (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/site/privacy (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link https://github.com/security (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://www.rackspace.com (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://www.rackspace.com%20 (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
    Skipping link http://www.rackspacecloud.com (from https://github.com/davidmarble/virtualenvwrapper-win/); not a file
  Could not find any downloads that satisfy the requirement virtualenvwrapper-win
No distributions at all found for virtualenvwrapper-win
Exception information:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pip\basecommand.py", line 126, in main
    self.run(options, args)
  File "C:\Python27\lib\site-packages\pip\commands\install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "C:\Python27\lib\site-packages\pip\req.py", line 954, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "C:\Python27\lib\site-packages\pip\index.py", line 152, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for virtualenvwrapper-win
```

**Comment by JithinOfficial** [comment]
Great .Me too have the same issue .Now its solved thanks buddy
